export enum ActionTypes {
  search_text_change,
  search_lang_change,
  search_sort_change,
  search_order_change,
  search_repositories,
  search_success,
  search_error,
  get_watching_repositories,
  get_watching_error,
  watch_repository,
  watch_repository_error,
  unwatch_repository,
  unwatch_repository_error,
  get_search_next,
  get_search_next_error,
}